[package]
name = "server-conf"
version = "0.7.3"
authors.workspace = true
edition.workspace = true

[dependencies]
config = "0.14"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
