[package]
name = "server-conf"
version = "0.9.1"
rust-version = "1.85"
authors.workspace = true
edition.workspace = true

[dependencies]
config = "0.15"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
