[package]
name = "server-conf"
version = "0.2.2"
authors = ["Chuma Takahiro <co.chuma@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10"
once_cell = "1.8"
serde = { version = "1.0", features = ["derive"] }
