[package]
name = "server-conf"
version = "0.6.0"
authors.workspace = true
edition.workspace = true

[dependencies]
config = "0.13"
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
