[package]
name = "server-conf"
version = "0.3.2"
authors = ["Chuma Takahiro <co.chuma@gmail.com>"]
edition = "2021"

[dependencies]
config = "0.13"
once_cell = "1.13"
serde = { version = "1.0", features = ["derive"] }
