[package]
name = "server-conf"
version = "0.8.0"
rust-version = "1.80"
authors.workspace = true
edition.workspace = true

[dependencies]
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
