[package]
name = "server-conf"
version = "0.3.1"
authors = ["Chuma Takahiro <co.chuma@gmail.com>"]
edition = "2021"

[dependencies]
config = "0.12"
once_cell = "1.10"
serde = { version = "1.0", features = ["derive"] }
